name: Publish Docker image to GitHub
on:
  push:

jobs:
  push_docker:
    name: Push Ubuntu Docker image to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set $GIT_SHORT_SHA
        run: echo "GIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.docker
          tags: docker.pkg.github.com/msyea/github-actions-runner/ubuntu-docker:${{ env.GIT_SHORT_SHA }}
          push: true
  push_dind:
    needs: push_docker
    name: Push Ubuntu DinD image to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set $GIT_SHORT_SHA
        run: echo "GIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull docker.pkg.github.com/msyea/github-actions-runner/ubuntu-docker:${{ env.GIT_SHORT_SHA }}
      - name: Push to GitHub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.dind
          tags: docker.pkg.github.com/msyea/github-actions-runner/ubuntu-dind:${{ env.GIT_SHORT_SHA }}
          push: true
          build-args: |
            REGISTRY=docker.pkg.github.com/msyea/github-actions-runner
            TAG=${{ env.GIT_SHORT_SHA }}
  push_gha:
    needs: [push_docker, push_dind]
    name: Push GitHub Actions runner image to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set $GIT_SHORT_SHA
        run: echo "GIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull docker.pkg.github.com/msyea/github-actions-runner/ubuntu-dind:${{ env.GIT_SHORT_SHA }}
      - name: Push to GitHub
        uses: docker/build-push-action@v2
        with:
          tags: docker.pkg.github.com/msyea/github-actions-runner/github-actions-runner:${{ env.GIT_SHORT_SHA }}
          push: true
          build-args: |
            REGISTRY=docker.pkg.github.com/msyea/github-actions-runner
            TAG=${{ env.GIT_SHORT_SHA }}
